### ISSUE TITLE
Add support for file attachments

### ISSUE THREAD

**Issue by tibetsprague** [holochain-apps/volla-messages#124]
- supports any file type
- download file
- file icon indicates file type (either with text or different icon)

**Comment by MasterK0927** [comment]
@mattyg While reviewing the codebase, I believe the following snippet is causing the main thread to block during large file uploads.

**Reference**: `handleImagesSelected` function in file [ui/src/routes/conversations/[id]/+page.svelte](https://github.com/holochain-apps/volla-messages/blob/069e8e0b2ee342adeec7cb6bdb4de08339e18575/ui/src/routes/conversations/%5Bid%5D/%2Bpage.svelte#L231)

- The use of `FileReader.readAsDataURL()` processes the entire file synchronously on the main thread, causing the UI to freeze when handling large uploads.

**Proposed Solutions**:
- Using `FileReader.readAsArrayBuffer()` instead of `readAsDataURL()` to avoid Base64 encoding overhead.
- Offloading file reading and processing to a Web Worker to prevent blocking the main thread.

What solutions do you think would work best to resolve this?
